global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "juneberries"
    static_configs:
      - targets:
        - "auth-api:8000"
        - "catalog-api:8000"
        - "orders-api:8000"
        - "reviews-api:8000"
